name: app-build-action-dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build-mac-ios-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # # APK签名设置（可选，如果 secrets 不存在可以注释掉）
      # - name: Download Android keystore
      #   id: android_keystore
      #   uses: timheuer/base64-to-file@v1.2
      #   with:
      #     fileName: keystore.jks
      #     encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      # - name: Create key.properties
      #   run: |
      #     echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > simple_live_app/android/key.properties
      #     echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> simple_live_app/android/key.properties
      #     echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> simple_live_app/android/key.properties
      #     echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> simple_live_app/android/key.properties

      # 设置Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # 设置Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      - name: Enable Flutter Mac Desktop
        run: flutter config --enable-macos-desktop

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # flutter_distributor
      - name: Install flutter_distributor
        run: |
          dart pub global activate flutter_distributor
      - name: Setup PATH
        run: echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

      # Build Android APK
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
